# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ASTR Auto Updater

on:
  # add manual trigger
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: 050644zf/ASTR-Script
        token: ${{secrets.PAT}}
    - uses: actions/checkout@v4
      with:
        repository: Kengxxiao/ArknightsGameData
        path: ArknightsGameData
    - uses: actions/checkout@v4
      with:
        repository: Kengxxiao/ArknightsGameData_YoStar
        path: ArknightsGameData_YoStar
    - uses: actions/checkout@v4
      with:
        repository: 050644zf/ArknightsStoryJson
        path: ArknightsStoryJson
        token: ${{secrets.PAT}}
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Updater
      run: |
        if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
          python ./jsonconvert.py -q
        else
          python ./jsonconvert.py -q --all
        fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: changes-and-deletion
        path: |
          ./changes.txt
          ./deletion.txt

    - name: Copy diff to tmp folder
      run: |
        bash ./copy_diff.sh
        
    - name: Push
      working-directory: ./ArknightsStoryJson
      run: |
        git push
